name: Release
on:
  push:
    tags:
      - "v*"
jobs:
  release:
    name: Release
    runs-on: windows-2025
    permissions:
      contents: write
    steps:
      - name: Code checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Setup Go
        uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version: 1.24.11

      - name: Build release binaries
        env:
          CGO_ENABLED: 0
          GOOS: windows
          GOARCH: amd64
          SRC_PATH: github.com/pterodactyl/wings
        run: |
          New-Item -ItemType Directory -Force dist | Out-Null
          go build -o dist/wings.exe -v -trimpath -ldflags="-s -w -X $env:SRC_PATH/system.Version=${{ github.ref_name }}" $env:SRC_PATH
          Compress-Archive -Path dist/wings.exe -DestinationPath dist/wings_windows_amd64.zip -Force

      - name: write changelog
        shell: bash
        run: |
          sed -n "/^## ${{ github.ref_name }}/,/^## /{/^## /b;p}" CHANGELOG.md > ./RELEASE_CHANGELOG

      - uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2.5.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          prerelease: ${{ contains(github.ref_name, 'rc') || contains(github.ref_name, 'beta') || contains(github.ref_name, 'alpha') }}
          body_path: ./RELEASE_CHANGELOG
          files: |
            dist/wings_windows_amd64.zip
